<?php
/**
 * Bazaar CLI — Developer-tooling commands.
 *
 * @package Bazaar
 */

declare( strict_types=1 );

namespace Bazaar\CLI\Traits;

defined( 'ABSPATH' ) || exit;

use Bazaar\AuditLog;
use Bazaar\CspPolicy;
use Bazaar\WareLoader;
use Bazaar\WareRegistry;
use Bazaar\RemoteRegistry;
use Bazaar\WareBundler;
use WP_CLI;
use WP_CLI\Utils;

/**
 * Developer-tooling commands: dev, scaffold, sign, keypair, types.
 */
trait WareDevTrait {

	/**
	 * Toggle dev mode for a ware.
	 *
	 * Usage: wp bazaar dev <start|stop> <slug> [<url>]
	 *
	 * @param array<int,string>    $args       Positional args: action, slug, optional dev URL.
	 * @param array<string,string> $assoc_args Named flags: --verbose for extra output.
	 */
	public function dev( array $args, array $assoc_args ): void {
		$action  = $args[0] ?? '';
		$slug    = sanitize_key( $args[1] ?? '' );
		$verbose = (bool) Utils\get_flag_value( $assoc_args, 'verbose', false );

		if ( '' === $slug ) {
			WP_CLI::error( __( 'Please provide a ware slug.', 'bazaar' ) );
			return;
		}

		if ( ! $this->registry->exists( $slug ) ) {
			WP_CLI::error(
				sprintf(
					/* translators: %s: ware slug */
					__( 'Ware "%s" not found.', 'bazaar' ),
					$slug
				)
			);
			return;
		}

		switch ( $action ) {
			case 'start':
				$this->dev_start( $slug, $args[2] ?? '' );
				if ( $verbose ) {
					WP_CLI::log( "Dev mode started for '{$slug}'." );
				}
				break;

			case 'stop':
				$this->dev_stop( $slug );
				if ( $verbose ) {
					WP_CLI::log( "Dev mode stopped for '{$slug}'." );
				}
				break;

			default:
				WP_CLI::error(
					sprintf(
						/* translators: %s: the unknown action the user typed */
						__( 'Unknown action "%s". Use: wp bazaar dev start <slug> <url>', 'bazaar' ),
						$action
					)
				);
		}
	}

	/**
	 * Generate a REST controller PHP stub and a matching TypeScript fetch helper.
	 *
	 * Usage: wp bazaar scaffold endpoint <Name> [--namespace=<ns>] [--route=<path>]
	 *
	 * @param array<int,string>    $args       Positional args: endpoint type, class name.
	 * @param array<string,string> $assoc_args Named flags: --namespace, --route.
	 */
	public function scaffold( array $args, array $assoc_args ): void {
		$name      = $args[0] ?? '';
		$action    = $args[1] ?? 'endpoint'; // Only 'endpoint' is supported for now.
		$namespace = sanitize_text_field( Utils\get_flag_value( $assoc_args, 'namespace', 'MyWare' ) );
		$route     = sanitize_text_field( Utils\get_flag_value( $assoc_args, 'route', '/items' ) );

		if ( '' === $name ) {
			WP_CLI::error( __( 'Usage: wp bazaar scaffold endpoint <name>', 'bazaar' ) );
		}

		$class_name = ucfirst( $name ) . 'Controller';
		$slug_name  = strtolower( preg_replace( '/([a-z])([A-Z])/', '$1-$2', $name ) ?? $name );
		$ts_fn_name = lcfirst( $name );
		$ns_slug    = strtolower( $namespace );

		$php = <<<PHP
<?php
/**
 * REST controller for {$name}.
 * Generated by: wp bazaar scaffold endpoint {$name}
 */

declare( strict_types=1 );

namespace {$namespace}\\REST;

use WP_REST_Controller;
use WP_REST_Server;
use WP_REST_Request;
use WP_REST_Response;

final class {$class_name} extends WP_REST_Controller {

	protected \$namespace = '{$ns_slug}/v1';
	protected \$rest_base = '{$slug_name}';

	public function register_routes(): void {
		register_rest_route( \$this->namespace, "/{$route}", [
			[
				'methods'             => WP_REST_Server::READABLE,
				'callback'            => [ \$this, 'get_items' ],
				'permission_callback' => [ \$this, 'auth' ],
			],
		] );
	}

	public function auth(): bool {
		return current_user_can( 'manage_options' );
	}

	public function get_items( WP_REST_Request \$request ): WP_REST_Response {
		// @todo Add your business logic here and replace this empty response.
		return new WP_REST_Response( [], 200 );
	}
}
PHP;

		$ts = <<<TS
import { wpFetch } from '@bazaar/client';

export interface {$class_name}Response {
  // @todo Replace `items: unknown[]` with the actual response shape.
  items: unknown[];
}

export async function {$ts_fn_name}(): Promise<{$class_name}Response> {
  return wpFetch<{$class_name}Response>( `/{$ns_slug}/v1{$route}` );
}
TS;

		$php_file = getcwd() . "/{$class_name}.php";
		$ts_file  = getcwd() . "/{$ts_fn_name}.ts";

		if ( ! function_exists( 'WP_Filesystem' ) ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
		}
		WP_Filesystem();
		global $wp_filesystem;
		if ( empty( $wp_filesystem ) ) {
			WP_CLI::error( __( 'WordPress filesystem could not be initialised.', 'bazaar' ) );
			return;
		}
		$wp_filesystem->put_contents( $php_file, $php, FS_CHMOD_FILE );
		$wp_filesystem->put_contents( $ts_file, $ts, FS_CHMOD_FILE );

		/* translators: %s: path to generated PHP file */
		WP_CLI::success( sprintf( __( 'Created %s', 'bazaar' ), $php_file ) );
		/* translators: %s: path to generated TypeScript file */
		WP_CLI::success( sprintf( __( 'Created %s', 'bazaar' ), $ts_file ) );
		WP_CLI::line( __( 'Register the controller in your plugin bootstrap with:', 'bazaar' ) );
		WP_CLI::line( "  add_action( 'rest_api_init', fn() => (new {$namespace}\\REST\\{$class_name}())->register_routes() );" );
	}

	/**
	 * Sign a .wp archive with a PEM private key and output the base64 signature.
	 *
	 * Usage: wp bazaar sign <archive.wp> [--key=<path>] [--passphrase=<pass>]
	 *
	 * @param array<int,string>    $args       Positional args: archive path.
	 * @param array<string,string> $assoc_args Named flags: --key, --passphrase.
	 */
	public function sign( array $args, array $assoc_args ): void {
		$realpath   = realpath( $args[0] ?? '' );
		$file       = $realpath ? $realpath : '';
		$key_path   = Utils\get_flag_value( $assoc_args, 'key', 'private.pem' );
		$passphrase = (string) Utils\get_flag_value( $assoc_args, 'passphrase', '' );

		if ( '' === $file || ! is_file( $file ) ) {
			WP_CLI::error( __( 'Archive file not found.', 'bazaar' ) );
		}

		$sig = $this->signer->sign( $file, $key_path, $passphrase );
		if ( is_wp_error( $sig ) ) {
			WP_CLI::error( $sig->get_error_message() );
			return;
		}

		WP_CLI::line( __( 'Signature (base64):', 'bazaar' ) );
		WP_CLI::line( $sig );
		WP_CLI::line( '' );
		WP_CLI::line( __( 'Add this to your manifest.json:', 'bazaar' ) );
		WP_CLI::line( '  "signature": "' . $sig . '"' );
	}

	/**
	 * Generate an RSA-2048 keypair for ware signing and write PEM files to disk.
	 *
	 * Usage: wp bazaar keypair [<output-dir>] [--output=<dir>]
	 *
	 * @param array<int,string>    $args       Optional positional output directory.
	 * @param array<string,string> $assoc_args Named flags: --output (defaults to cwd).
	 */
	public function keypair( array $args, array $assoc_args ): void {
		$dir = rtrim( $args[0] ?? Utils\get_flag_value( $assoc_args, 'output', '.' ), '/' );

		$pair = $this->signer->generate_keypair();
		if ( is_wp_error( $pair ) ) {
			WP_CLI::error( $pair->get_error_message() );
			return;
		}

		$priv_path = $dir . '/private.pem';
		$pub_path  = $dir . '/public.pem';

		if ( ! function_exists( 'WP_Filesystem' ) ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
		}
		WP_Filesystem();
		global $wp_filesystem;
		if ( empty( $wp_filesystem ) ) {
			WP_CLI::error( __( 'WordPress filesystem could not be initialised.', 'bazaar' ) );
			return;
		}
		$wp_filesystem->put_contents( $priv_path, $pair['private'], FS_CHMOD_FILE );
		$wp_filesystem->put_contents( $pub_path, $pair['public'], FS_CHMOD_FILE );
		$wp_filesystem->chmod( $priv_path, 0600 );

		/* translators: %s: path to private key file */
		WP_CLI::success( sprintf( __( 'Private key: %s (keep this secret!)', 'bazaar' ), $priv_path ) );
		/* translators: %s: path to public key file */
		WP_CLI::success( sprintf( __( 'Public key:  %s', 'bazaar' ), $pub_path ) );
		WP_CLI::line( __( 'Store the public key in Bazaar → Settings → Signing Public Key.', 'bazaar' ) );
	}

	/**
	 * Generate TypeScript type definitions from a ware's manifest (config, events, jobs).
	 *
	 * Usage: wp bazaar types <slug> [--out=<file>]
	 *
	 * @param array<int,string>    $args       Positional args: ware slug.
	 * @param array<string,string> $assoc_args Named flags: --out (writes to file instead of stdout).
	 */
	public function types( array $args, array $assoc_args ): void {
		if ( empty( $args[0] ) ) {
			WP_CLI::error( 'Please provide a ware slug.' );
		}
		$slug = sanitize_key( $args[0] );
		$ware = $this->registry->get( $slug );
		if ( null === $ware ) {
			WP_CLI::error( "Ware '{$slug}' not found." );
		}

		$lines = array( "// Auto-generated by: wp bazaar types {$slug}", '// Do not edit manually.', '', 'declare module \'@bazaar/wares/' . $slug . "' {" );

		// Config types.
		$settings = (array) ( $ware['settings'] ?? array() );
		if ( $settings ) {
			$lines[] = '  export interface Config {';
			foreach ( $settings as $field ) {
				$key  = $field['key'] ?? '';
				$type = match ( $field['type'] ?? 'text' ) {
					'number'   => 'number',
					'checkbox' => 'boolean',
					default    => 'string',
				};
				$opt     = empty( $field['required'] ) ? '?' : '';
				$lines[] = "    $key{$opt}: {$type};";
			}
			$lines[] = '  }';
			$lines[] = '';
		}

		// Bus events.
		$events = (array) ( $ware['events'] ?? array() );
		if ( $events ) {
			$lines[] = '  export type BusEvent =';
			$union   = array_map( fn( $e ) => "    | '" . addslashes( $e ) . "'", $events );
			$lines[] = implode( "\n", $union ) . ';';
			$lines[] = '';
		}

		// Job IDs.
		$jobs = (array) ( $ware['jobs'] ?? array() );
		if ( $jobs ) {
			$ids     = array_map( fn( $j ) => "'" . addslashes( $j['id'] ?? '' ) . "'", $jobs );
			$lines[] = '  export type JobId = ' . implode( ' | ', $ids ) . ';';
			$lines[] = '';
		}

		$lines[] = '}';
		$output  = implode( "\n", $lines ) . "\n";

		$out = Utils\get_flag_value( $assoc_args, 'out', '' );
		if ( $out ) {
			if ( ! function_exists( 'WP_Filesystem' ) ) {
				require_once ABSPATH . 'wp-admin/includes/file.php';
			}
			WP_Filesystem();
			global $wp_filesystem;
			if ( empty( $wp_filesystem ) ) {
				WP_CLI::error( __( 'WordPress filesystem could not be initialised.', 'bazaar' ) );
				return;
			}
			$wp_filesystem->put_contents( $out, $output, FS_CHMOD_FILE );
			WP_CLI::success( "Types written to {$out}" );
		} else {
			WP_CLI::log( $output );
		}
	}

	// ── Private helpers ───────────────────────────────────────────────────────

	/**
	 * Activate dev mode: store the Vite dev server URL in the ware registry.
	 *
	 * @param string $slug Ware slug.
	 * @param string $url  Local dev server URL (e.g. http://localhost:5173).
	 */
	private function dev_start( string $slug, string $url ): void {
		if ( '' === $url ) {
			WP_CLI::error( __( 'Please provide the dev server URL, e.g. http://localhost:5173.', 'bazaar' ) );
			return;
		}

		if ( ! filter_var( $url, FILTER_VALIDATE_URL ) ) {
			WP_CLI::error(
				sprintf(
					/* translators: %s: URL provided by the user */
					__( '"%s" is not a valid URL.', 'bazaar' ),
					$url
				)
			);
			return;
		}

		if ( ! $this->registry->set_dev_url( $slug, $url ) ) {
			WP_CLI::error(
				sprintf(
					/* translators: %s: ware slug */
					__( 'Could not set dev URL for "%s".', 'bazaar' ),
					$slug
				)
			);
			return;
		}

		$debug_status = ( defined( 'WP_DEBUG' ) && (bool) constant( 'WP_DEBUG' ) )
			? __( 'WP_DEBUG is true — dev mode will be active immediately.', 'bazaar' )
			: __( 'Note: WP_DEBUG is false on this site. Set WP_DEBUG=true for dev mode to take effect.', 'bazaar' );

		WP_CLI::success(
			sprintf(
				/* translators: 1: ware slug, 2: dev server URL */
				__( 'Dev mode started for "%1$s" → %2$s', 'bazaar' ),
				$slug,
				$url
			)
		);
		WP_CLI::line( $debug_status );
		WP_CLI::line(
			sprintf(
				/* translators: %s: ware slug */
				__( 'Stop with: wp bazaar dev stop %s', 'bazaar' ),
				$slug
			)
		);
	}

	/**
	 * Deactivate dev mode, returning the ware to its installed files.
	 *
	 * @param string $slug Ware slug.
	 */
	private function dev_stop( string $slug ): void {
		if ( ! $this->registry->clear_dev_url( $slug ) ) {
			WP_CLI::error(
				sprintf(
					/* translators: %s: ware slug */
					__( 'Could not clear dev URL for "%s" (was it in dev mode?).', 'bazaar' ),
					$slug
				)
			);
			return;
		}

		WP_CLI::success(
			sprintf(
				/* translators: %s: ware slug */
				__( 'Dev mode stopped for "%s". Ware is back on its installed files.', 'bazaar' ),
				$slug
			)
		);
	}
}
